apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
    image: mysql:latest
    env:
        - name: "MYSQL_USER"
          value: "user"
        - name: "MYSQL_PASSWORD"
          value: "password"
        - name: "MYSQL_DATABASE"
          value: "sample"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "supersecret"
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
    ports:
      - containerPort: 3306
