apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-nginx 
  template:
    metadata:
      labels:
        app: deployment-nginx 
    spec:
      containers:
      - name: deployment-nginx 
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
