apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  type: NodePort
  selector:
    app: deployment-nginx #encaminha os requests para os Pods com Labels desse valor
  ports:
  - port: 80 #numero da porta que exposta internamente no Cluster
    targetPort: 80 #define a porta que os pods estão escutando.
    #nodePort: <nodePort> #acessa o servico usando este numero externo de porta
